# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChangeFly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=150)),
                ('rounded_amount', models.IntegerField(max_length=150)),
                ('donation', models.FloatField(max_length=150)),
                ('date', models.DateField(max_length=150)),
                ('transactionid', models.IntegerField(max_length=150)),
            ],
        ),
    ]
