# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChangeFly', '0002_customer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='date',
            field=models.CharField(max_length=150),
        ),
    ]
