# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChangeFly', '0003_auto_20171112_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_info',
            name='storename',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_info',
            name='rounded_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer_info',
            name='transactionid',
            field=models.IntegerField(),
        ),
    ]
